apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openanonymiser-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ConductionNL/OpenAnonymiser.git
    targetRevision: staging  # ← Staging wijst naar staging branch  
    path: charts/openanonymiser
    helm:
      valueFiles:
        - values-staging.yaml  # ← Use staging-specific values
      parameters:
        - name: image.tag
          value: v1.2.0
        - name: image.pullPolicy
          value: IfNotPresent
        - name: ingress.hosts[0].host
          value: api.openanonymiser.accept.commonground.nu
        - name: ingress.tls[0].secretName
          value: openanonymiser-accept-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: openanonymiser-staging  # ← Staging namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true